import 'package:flutter/material.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedLipsticksWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedMakeuppriceWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedLipglossWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedFoundationsWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedViewall1Widget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedPerfumepriceWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedLipglosspriceWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedSearchIconWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedAllCategoriesTextWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedSettingsWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedViewall2Widget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedTodaysSpecialWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedLotionsWidget1.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedLipsticksWidget1.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedMakeupWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedPerfumeWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedSearchboxWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedSearchTextWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedShoppingCartWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedLotionsWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedFavoritesWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedMyAccountWidget.dart';
import 'package:flutterapp/heathermataruse_miniprojectapp/generatedproductspagewidget/generated/GeneratedFoundationsWidget1.dart';

/* Frame ProductsPage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductsPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(63, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 9.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 39.0,
                child: GeneratedSearchboxWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 18.0,
                child: GeneratedSearchTextWidget(),
              ),
              Positioned(
                left: 317.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSearchIconWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 80.0,
                child: GeneratedMakeupWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 29.0,
                child: GeneratedAllCategoriesTextWidget(),
              ),
              Positioned(
                left: 280.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 21.0,
                child: GeneratedViewall2Widget(),
              ),
              Positioned(
                left: 273.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 21.0,
                child: GeneratedViewall1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 17.0,
                child: GeneratedLipsticksWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 16.0,
                child: GeneratedFoundationsWidget(),
              ),
              Positioned(
                left: 261.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 24.0,
                child: GeneratedLotionsWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 47.0,
                child: GeneratedMakeuppriceWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 35.0,
                child: GeneratedLipglosspriceWidget(),
              ),
              Positioned(
                left: 250.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 37.0,
                child: GeneratedPerfumepriceWidget(),
              ),
              Positioned(
                left: 175.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedFavoritesWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedShoppingCartWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 251.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedMyAccountWidget(),
              ),
              Positioned(
                left: 311.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedSettingsWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 37.0,
                child: GeneratedTodaysSpecialWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 80.0,
                child: GeneratedLipsticksWidget1(),
              ),
              Positioned(
                left: 241.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 80.0,
                child: GeneratedLotionsWidget1(),
              ),
              Positioned(
                left: 125.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 80.0,
                child: GeneratedFoundationsWidget1(),
              ),
              Positioned(
                left: 245.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 80.0,
                child: GeneratedPerfumeWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 80.0,
                child: GeneratedLipglossWidget(),
              )
            ]),
      ),
    ));
  }
}
